name: dot_know
description: ". know"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg:
  intl:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
  firebase_core:
  firebase_auth:
  get_it:
  dartz:
#  provider: ^6.1.2
#  shared_preferences: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/fonts/
     - assets/vectors/
     - assets/images/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300
