// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9UwQA62bagktFhDqL5uhom5e_ZTfuHo',
    appId: '1:909386468442:web:e93a5f8abe96cd2a0a1c63',
    messagingSenderId: '909386468442',
    projectId: 'sp-app-100021996',
    authDomain: 'sp-app-100021996.firebaseapp.com',
    storageBucket: 'sp-app-100021996.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWlE01w_l4Qy2gPzk3xGnzZufQjXr7Ec',
    appId: '1:909386468442:android:732d83236e4ba5e20a1c63',
    messagingSenderId: '909386468442',
    projectId: 'sp-app-100021996',
    storageBucket: 'sp-app-100021996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBfsHLcrpEWVzCF37rKRxvapzc-cW0EI',
    appId: '1:909386468442:ios:d4586c7e2e0129a60a1c63',
    messagingSenderId: '909386468442',
    projectId: 'sp-app-100021996',
    storageBucket: 'sp-app-100021996.firebasestorage.app',
    iosBundleId: 'com.ovs.dotKnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUBfsHLcrpEWVzCF37rKRxvapzc-cW0EI',
    appId: '1:909386468442:ios:d4586c7e2e0129a60a1c63',
    messagingSenderId: '909386468442',
    projectId: 'sp-app-100021996',
    storageBucket: 'sp-app-100021996.firebasestorage.app',
    iosBundleId: 'com.ovs.dotKnow',
  );
}
